import type { Metadata } from "next";
import { Inter, Antonio } from "next/font/google"; // Added Antonio
import "./globals.css";
import ResponsiveNav from "@/components/Home/Navbar/ResponsiveNav";

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-inter",
});

const antonio = Antonio({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-antonio",
});

export const metadata: Metadata = {
  title: "Sirzan-Chaudhary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${antonio.variable} antialiased bg-[#1A1A1B] text-white`}
        suppressHydrationWarning
      >
        <ResponsiveNav />
        {children}
        <footer />

      </body>
    </html>
  );
}
